version: "3.7"
services:
  currencies_api:
    image: pedromihael/currencies-converter-api:v3
    build: 
      context: .
      dockerfile: dev.dockerfile
    command: sh -c "yarn start"
    environment:
      CURRENCIES_API_PORT: 3000
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      MONGODB_URL: mongodb://mongodb:27017
      REDIS_HOST: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
    ports:
      - 3000:3000
    deploy:
       restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - .:/usr/app
      
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb_data_container: