apiVersion: v1
kind: Pod
metadata:
  name: currencies-converter-pod
  labels:
    name: currencies-converter-pod
    app: currencies-converter-api
spec:
  containers:
    - name: currencies-converter-pod
      image: pedromihael/currencies-converter-api:latest
      ports:
        - containerPort: 3000