apiVersion: v1
kind: Service
metadata:
  name: currencies-converter-pod
  labels:
    name: currencies-converter-pod
    app: currencies-converter-pod
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: currency-converter-pod
    app: currencies-converter-pod