name: Docker Build Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRODUCT_REPO_NAME: ${{secrets.PRODUCT_REPO_NAME}}
jobs:
  create-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Work Dir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $PRODUCT_REPO_NAME
      - name: Docker login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build api docker image
        run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"
      - name: Push api service docker image
        run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"
      # - name: Build database docker image
      #   run: docker build . --file Dockerfile.mongodb -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME-database:latest"
      # - name: Push database docker image
      #   run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME-database:latest"
deployment:
    needs: [create-images]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/