name: Docker Build Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRODUCT_REPO_NAME: ${{secrets.PRODUCT_REPO_NAME}}
  SERVICE_FIXER_IO_ACCESS_KEY: ${{secrets.SERVICE_FIXER_IO_ACCESS_KEY}}
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
  REDIS_URL: ${{secrets.REDIS_URL}}
  IMAGE_VERSION: v6

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Work Dir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $PRODUCT_REPO_NAME
      - name: Docker login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build api docker image
        run: docker build . -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:$IMAGE_VERSION" --build-arg mongo_url=$MONGODB_URL --build-arg mongo_password=$MONGODB_PASSWORD --build-arg fixer_accesskey=$SERVICE_FIXER_IO_ACCESS_KEY --build-arg redis_url=$REDIS_URL
      - name: Push api service docker image
        run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:$IMAGE_VERSION"

  deployment:
    needs: [create-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }} 
          ZONE_NAME: us-central1
        with:
          args: apply -f k8s/